# -*- coding: utf-8 -*-
"""Examens-SCRIPT2 Exceptions- Amina LEK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/168ss-Ijq5AfFuMqrxHFJ4b25peznAgR-
"""

def polynome (x): 
     
    if type (x) == str :
            print ("mpossible de saisir une chaine de caractére, saisir valeurs numérique")
            while type(x) == str :
                x = int(input('Entrez une valeur numérique pour x ='))
        
                
    elif type(x) == complex :
          print (" Nous ne pouvons pas choiri un nombre complexe")
          while (type(x) == complex) : 
              
              x = int(input(" Veuillez saisir un nombre numérique pour x"))
              

    elif (x < 0) :
        print (" nous ne pouvons pas choisir un numéro négatif")
        while (x<0):
                  x = int(input("veuillez entrer un nombre positif pour x"))
                        


    elif (len(str(x)) > 10) :
          #print (" Nous ne pouvons pas choisir un nombre trop grand")
          
          while len(str(x) > 10):
              x = int(input("LA valeur que vous avez tapez est supérieur à 10 unités"))

  
    elif (len(str(x)) < 0.5) :
          #print (" Nous ne pouvons pas choisir un nombre trop petit")
    
    
 return x**3 - 1.5*x**2 - 6*x + 5 
 


print (polynome(-1))