# -*- coding: utf-8 -*-
"""Examens PYTHON-SCRIPT 1 Fonction- Amina LEK.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TJZy7OSd5e9FA10qJu1A5EZZyHTAWGdv

A) Implémenter une fonction polynomiale
"""

def polynome (x):
  return x**3 - 1.5*x**2 - 6*x + 5 

print (polynome(5))

"""B) Implémenter la fonction factorielle"""

def factoriel (n):
  if n == 0 :
    return (1)
  else : 
    a = 1
    return n * factoriel (n-1)

factoriel (5)

"""C) Implémenter la suite de Fibonnaci"""

def fibo (r):
  if r <= 1 :
    return r
  else:
    return fibo (r-1) + fibo (r-2)

r = int (input (" entrez un nombre : "))

print (" la suite fibonaci est :")

for t in range (r):
   print (fibo(t))